/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE autoBaseService PLEASE EDIT ../auto.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Auto } from '../../domain/auto-motor_db/auto';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Auto.service.ts
 */

/*
 * SCHEMA DB Auto
 *
	{
		cc: {
			type: 'String'
		},
		colore: {
			type: 'String'
		},
		proprietario: {
			type: 'Integer'
		},
		tipo: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		FK_PEROSNA_AUTO: {
			type: Schema.ObjectId,
			ref : "Persona"
		},
	}
 *
 */
@Injectable()
export class AutoBaseService {

    contextUrl: string = environment.endpoint + '/Auto';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * AutoService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Auto): Observable<Auto> {
        return this.http
            .post<Auto>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * AutoService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * AutoService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Auto> {
        return this.http
            .get<Auto>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * AutoService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Auto[]> {
        return this.http
            .get<Auto[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * AutoService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Auto): Observable<Auto> {
        return this.http
            .post<Auto>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
