package com.automotor.db.automotor_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE PersonaBase PLEASE EDIT ../Persona.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Persona object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.automotor.db.automotor_db.entity.Persona;

public class PersonaBase implements RowMapper<Persona>{
	
	private Long _id;
	
	// Attributes
    private String cognome;
    private Double eta;
    private String mail;
    private String nome;
	
	// Relations FK_PEROSNA_AUTO
	private String FK_PEROSNA_AUTO;
	
	
	
	@Override
	public Persona mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Persona obj = new Persona();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setCognome(rs.getString("cognome"));
			obj.setEta(rs.getDouble("eta"));
			obj.setMail(rs.getString("mail"));
			obj.setNome(rs.getString("nome"));
			
        	
        	// Relations 1:m FK_PEROSNA_AUTO
			obj.setFK_PEROSNA_AUTO(rs.getString("FK_PEROSNA_AUTO"));
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getCognome() {
		return cognome;
	}


	public void setCognome(String cognome) {
		this.cognome = cognome;
	}
	public Number getEta() {
		return eta;
	}


	public void setEta(Number eta) {
		this.eta = eta;
	}
	public String getMail() {
		return mail;
	}


	public void setMail(String mail) {
		this.mail = mail;
	}
	public String getNome() {
		return nome;
	}


	public void setNome(String nome) {
		this.nome = nome;
	}
	
    
    // Relations 1:m FK_PEROSNA_AUTO
	public String getFK_PEROSNA_AUTO() {
		return FK_PEROSNA_AUTO;
	}

	public void setFK_PEROSNA_AUTO(String FK_PEROSNA_AUTO) {
		this.FK_PEROSNA_AUTO = FK_PEROSNA_AUTO;
	}
    
    
    
    
}